-- pandoc lua filter for thesis docx conversion
-- * labelmap.lua (generated by build) provides label -> number
-- * fix eqref/ref link text for equation labels (pandoc emits "[key]")
-- * anchor DisplayMath blocks carrying \label inside a Div with that id
--   (label stripped to avoid re-wrapping under topdown traversal)
-- * 'tcolorboxdoc' env -> 'framed-note' div (styled in post-process)
-- * prepend TOC field + LOF/LOT placeholders at document start

local labelmap = {}
local f = io.open("labelmap.lua", "r")
if f then
  labelmap = load(f:read("*a"), "labelmap", "t", _G)()
  f:close()
end

local function is_stub(text)
  return text:match("^%[.+%]$") ~= nil
end

local function prepend_front(doc)
  local front = {
    pandoc.Header(1,
      {pandoc.Str "MỤC LỤC"},
      pandoc.Attr("", {"unnumbered"}, {})),
    pandoc.RawBlock("openxml",
      '<w:p><w:r><w:fldChar w:fldCharType="begin"/></w:r>' ..
      '<w:r><w:instrText xml:space="preserve"> TOC \\o "1-3" \\h \\z \\u </w:instrText></w:r>' ..
      '<w:r><w:fldChar w:fldCharType="separate"/></w:r>' ..
      '<w:r><w:t>Nhấp chuột phải → Cập nhật trường để hiển thị mục lục.</w:t></w:r>' ..
      '<w:r><w:fldChar w:fldCharType="end"/></w:r></w:p>'),
    pandoc.Header(1,
      {pandoc.Str "DANH MỤC HÌNH VẼ"},
      pandoc.Attr("", {"unnumbered"}, {})),
    pandoc.RawBlock("openxml",
      '<w:p><w:r><w:t>DANH_MUC_HINH_PLACEHOLDER</w:t></w:r></w:p>'),
    pandoc.Header(1,
      {pandoc.Str "DANH MỤC BẢNG BIỂU"},
      pandoc.Attr("", {"unnumbered"}, {})),
    pandoc.RawBlock("openxml",
      '<w:p><w:r><w:t>DANH_MUC_BANG_PLACEHOLDER</w:t></w:r></w:p>'),
  }
  for i = #front, 1, -1 do
    table.insert(doc.blocks, 1, front[i])
  end
  return doc
end

local function make_blocks(blocks)
  local out = {}
  for _, b in ipairs(blocks) do
    -- anchor math carrying \label
    if b.t == "Para" or b.t == "Plain" then
      local key = nil
      for _, i in ipairs(b.content) do
        if i.t == "Math" then
          key = i.text:match("\\label{([^}]+)}") or key
        end
      end
      if key then
        for _, i in ipairs(b.content) do
          if i.t == "Math" then
            i.text = i.text:gsub("\\label{[^}]+}", "")
          end
        end
        table.insert(out, pandoc.Div({b}, pandoc.Attr(key, {}, {})))
      else
        table.insert(out, b)
      end
    else
      table.insert(out, b)
    end
  end
  return out
end

local function fix_div(el)
  if el.classes:includes("tcolorboxdoc") then
    el.classes = {"framed-note"}
    return el
  end
end

local function fix_link(el)
  local ref = el.attributes["reference"]
  if ref and labelmap[ref] then
    if el.attributes["reference-type"] == "eqref" then
      el.content = {pandoc.Str("(" .. labelmap[ref] .. ")")}
      return el
    end
    -- aux is ground truth (appendix "A" vs pandoc's sequential "7")
    el.content = {pandoc.Str(labelmap[ref])}
    return el
  end
  return el
end

return {
  { traverse = "topdown",
    Blocks = make_blocks,
    Div = fix_div,
    Link = fix_link,
    Pandoc = prepend_front }
}
